version: '3'
services:
  db:
    build: ./database-service
    environment:
      POSTGRES_DB: projectgoogle
      POSTGRES_PASSWORD: qwerty123
      POSTGRES_USER: user
    volumes:
      - ./database-service/seeder.sql:/docker-entrypoint-initdb.d/dump.sql
  app:
    build: ./
    restart: on-failure
    environment:
        POSTGRES_DB: projectgoogle
        POSTGRES_PASSWORD: qwerty123
        POSTGRES_USER: user
    ports:
      - "9090:9090"
    depends_on:
        - db
    links:
      - db:db
